from funciones import *

def EleccionTemas(self,eleccion, root, tit, tabla, temas, desc,tema1, tema2, tema3, boton1, boton2, boton3):
    if self.app.eleccion.get() == 1:
                    print("Tema Oscuro")
                    self.app.root.config(bg ="black")
                    self.app.tit.config(bg ="black", foreground ="white")
                    self.app.tabla.config(bg ="white", foreground = "black")
                    self.app.temas.config(bg ="white", foreground = "black")
                    self.app.desc.config(bg ="black", foreground = "white")
                    self.app.tema1.config(bg ="black", foreground ="white")
                    self.app.tema2.config(bg ="black", foreground ="white")
                    self.app.tema3.config(bg ="black", foreground ="white")
                    self.app.boton1.config(bg ="white", foreground ="black")
                    self.app.boton2.config(bg ="white", foreground ="black")
                    self.app.boton3.config(bg ="white", foreground ="black")
    elif self.app.eleccion.get() == 2:
                    print("Tema Clásico")
                    self.app.root.config(bg ="snow3")
                    self.app.tabla.config(bg ="snow4", foreground = "black")
                    self.app.temas.config(bg ="snow4", foreground = "black")
                    self.app.tit.config(bg ="snow3", foreground ="black")
                    self.app.desc.config(bg ="snow3", foreground = "black")
                    self.app.tema1.config(bg ="snow3", foreground ="black")
                    self.app.tema2.config(bg ="snow3", foreground ="black")
                    self.app.tema3.config(bg ="snow3", foreground ="black")
                    self.app.boton1.config(bg ="white", foreground ="black")
                    self.app.boton2.config(bg ="white", foreground ="black")
                    self.app.boton3.config(bg ="white", foreground ="black")
    elif self.app.eleccion.get() == 3:
                    print("Tema Sorpresa")
                    self.app.root.config(bg ="snow3")
                    self.app.tabla.config(bg ="maroon", foreground = "white")
                    self.app.temas.config(bg ="maroon", foreground = "white")
                    self.app.tit.config(bg ="snow3", foreground ="black")
                    self.app.desc.config(bg ="snow3", foreground = "black")
                    self.app.tema1.config(bg ="snow3", foreground ="black")
                    self.app.tema2.config(bg ="snow3", foreground ="black")
                    self.app.tema3.config(bg ="snow3", foreground ="black")
                    self.app.boton1.config(bg ="maroon", foreground ="white")
                    self.app.boton2.config(bg ="maroon", foreground ="white")
                    self.app.boton3.config(bg ="maroon", foreground ="white")